global:
  scrape_interval: 15s   # How often to scrape targets by default
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']  # Make sure Traefik metrics are exposed on port 8080
    metrics_path: '/metrics'

  # Scrape Vaultwarden metrics
  - job_name: 'vaultwarden'
    static_configs:
      - targets: ['vaultwarden:3030']  # Replace with the port where Vaultwarden metrics are exposed
    metrics_path: '/metrics'

  # Scrape Jenkins metrics
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']  # Jenkins should be exposing metrics on this port
    metrics_path: '/prometheus'  # Ensure the Prometheus plugin is installed in Jenkins

  # Scrape Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']  # Grafana metrics are exposed on port 3000
    metrics_path: '/metrics'
    basic_auth:
      username: fortis   # Replace with actual Grafana username
      password: '1234admin'   # Replace with actual Grafana password
